
baseurl: "https://uncertainty-cv.github.io/2026/"
color-scheme: "#1a2090" #the scheme can be any HEX code like "#334279"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache

title: "5th Workshop on Uncertainty Quantification for Computer Vision"
subtitle: "[ECCV 2026 Workshop](https://cvpr.thecvf.com/Conferences/2025) <br> September 8/9th 2026, Full day <br>"

shorttitle: "UNCV Workshop @ ECCV 2026"
information: "ECCV 2026 Workshop on Uncertainty Quantification for Computer Vision." 

organizers: "UNCV Organizers"

deadlines:
  - item: Submission deadline
    date: "June 17th, 2026"
  
  - item: Notification of acceptance
    date: "August 7th, 2026 (tentative)"

  - item: Camera-ready deadline
    date: "August 15th, 2026 (tentative)"

